language: node_js
node_js:
  - 18.18.0

branches:
  only:
    - main

cache:
  directories:
    - node_modules

before_install:
  # - openssl aes-256-cbc -K $encrypted_<your_encrypted_key>_key -iv $encrypted_<your_encrypted_key>_iv -in travis_deploy_key.enc -out ~/.ssh/travis_deploy_key -d
  # - chmod 600 ~/.ssh/travis_deploy_key
  # - echo -e "Host <your-ec2-ip>\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - npm install

script:
  - ng build --prod

deploy:
  provider: script
  script: scp -i ~/.ssh/travis_deploy_key -r dist/* ec2-user@<your-ec2-ip>:/path/to/remote/directory
